service: graphql-api
provider:
  name: aws
  profile: serverless
  runtime: nodejs6.10

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: get